"""PDF report generation (reportlab)."""
from __future__ import annotations

import io
from datetime import datetime
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def generate_report_pdf(report: dict[str, Any], patient: dict[str, Any]) -> bytes:
    """Build a professional, printable PDF screening report."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4, topMargin=18 * mm, bottomMargin=18 * mm,
        leftMargin=16 * mm, rightMargin=16 * mm,
    )
    styles = getSampleStyleSheet()
    title = ParagraphStyle("title", parent=styles["Title"], fontSize=20, spaceAfter=2)
    sub = ParagraphStyle("sub", parent=styles["Normal"], textColor=colors.grey, fontSize=9)
    h2 = ParagraphStyle("h2", parent=styles["Heading2"], fontSize=12, spaceBefore=10, spaceAfter=4)
    body = ParagraphStyle("body", parent=styles["Normal"], fontSize=9.5, leading=14)

    story = [
        Paragraph("NeuroLens AI — Digital Neurological Screening Report", title),
        Paragraph(
            f"{patient.get('name', 'Patient')} · {datetime.now().strftime('%d %b %Y, %H:%M')} · "
            "Screening aid — not a diagnostic tool",
            sub,
        ),
        Spacer(1, 6),
        Paragraph(
            f"Overall score: <b>{report.get('overall')}/100</b> &nbsp;·&nbsp; "
            f"Risk: <b>{report.get('risk')}</b> &nbsp;·&nbsp; Confidence: {report.get('confidence')}%",
            body,
        ),
    ]

    # domain table
    rows = [["Domain", "Score", "Confidence"]]
    for domain, score in sorted(report.get("domain_scores", {}).items()):
        rows.append([domain, f"{score}/100", f"{report.get('confidence', 0)}%"])
    table = Table(rows, colWidths=[70 * mm, 40 * mm, 40 * mm])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0b1120")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f1f5f9")]),
            ]
        )
    )
    story.append(Spacer(1, 6))
    story.append(table)

    story.append(Paragraph("Explanations", h2))
    for e in report.get("explanations", []):
        story.append(Paragraph(f"• {e}", body))

    story.append(Paragraph("Recommendations", h2))
    for r in report.get("recommendations", []):
        story.append(Paragraph(f"• {r}", body))

    if report.get("doctor_summary"):
        story.append(Paragraph("Doctor summary", h2))
        story.append(Paragraph(report["doctor_summary"], body))

    story.append(Spacer(1, 10))
    story.append(
        Paragraph(
            "This report is generated by an AI-assisted screening platform. It does not constitute "
            "a medical diagnosis. Please consult a qualified neurologist for any clinical decisions.",
            ParagraphStyle("disc", parent=body, textColor=colors.HexColor("#92400e"), fontSize=8.5),
        )
    )

    doc.build(story)
    return buf.getvalue()
