import { useState } from "react";
import { Bell, BellRing, CheckCheck, Pill, TrendingDown, CalendarClock, ScanLine } from "lucide-react";
import { Badge, Card, DisclaimerBanner, PageHeading, cn } from "../components/ui";
import { MotionPage } from "../components/Layout";

interface Notice {
  id: number;
  kind: "trend" | "reminder" | "medication" | "family";
  title: string;
  body: string;
  time: string;
  unread: boolean;
}

const INITIAL: Notice[] = [
  { id: 1, kind: "trend", title: "Tremor trend flagged", body: "Your tremor score declined 7 points across the last 2 weeks. Consider discussing this with your neurologist.", time: "2h ago", unread: true },
  { id: 2, kind: "reminder", title: "Weekly screening due", body: "You haven't screened this week. A 5-minute session keeps your trend line accurate.", time: "1d ago", unread: true },
  { id: 3, kind: "medication", title: "Dose log reminder", body: "Log your after-dose response to keep the medication effectiveness report up to date.", time: "2d ago", unread: false },
  { id: 4, kind: "family", title: "Family alert", body: "A family member viewed your latest report and requested a check-in call.", time: "3d ago", unread: false },
];

const KIND_STYLE: Record<Notice["kind"], { icon: React.ReactNode; cls: string }> = {
  trend: { icon: <TrendingDown size={15} />, cls: "bg-rose-500/15 text-rose-300" },
  reminder: { icon: <CalendarClock size={15} />, cls: "bg-brand-500/15 text-brand-300" },
  medication: { icon: <Pill size={15} />, cls: "bg-amber-400/15 text-amber-300" },
  family: { icon: <BellRing size={15} />, cls: "bg-teal-500/15 text-teal-300" },
};

export default function Notifications() {
  const [notices, setNotices] = useState<Notice[]>(INITIAL);
  const unread = notices.filter((n) => n.unread).length;

  return (
    <MotionPage>
      <PageHeading
        title="Notifications"
        subtitle="Trend alerts, screening reminders and family updates — delivered via push (FCM) in production."
        action={
          unread > 0 ? (
            <button
              onClick={() => setNotices((ns) => ns.map((n) => ({ ...n, unread: false })))}
              className="inline-flex items-center gap-2 rounded-xl border border-white/12 px-4 py-2 text-sm text-white/70 hover:bg-white/5"
            >
              <CheckCheck size={15} /> Mark all read
            </button>
          ) : (
            <Badge tone="teal">
              <Bell size={12} /> All caught up
            </Badge>
          )
        }
      />

      <Card>
        <div className="space-y-2">
          {notices.map((n) => {
            const s = KIND_STYLE[n.kind];
            return (
              <div
                key={n.id}
                className={cn(
                  "flex items-start gap-3.5 rounded-xl border px-4 py-3.5",
                  n.unread ? "border-brand-400/25 bg-brand-500/8" : "border-white/8 bg-ink-900/50"
                )}
              >
                <span className={cn("mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-xl", s.cls)}>
                  {s.icon}
                </span>
                <div className="flex-1">
                  <p className="flex items-center gap-2 text-sm font-medium text-white/90">
                    {n.title}
                    {n.unread && <span className="h-1.5 w-1.5 rounded-full bg-brand-400" />}
                  </p>
                  <p className="mt-0.5 text-xs leading-relaxed text-white/50">{n.body}</p>
                </div>
                <span className="shrink-0 text-[11px] text-white/35">{n.time}</span>
              </div>
            );
          })}
        </div>
        <div className="mt-4 flex items-center gap-2 rounded-xl border border-white/8 bg-ink-900/50 px-4 py-3 text-xs text-white/45">
          <ScanLine size={14} className="text-brand-300" />
          Notifications are generated by the trend engine when scores cross configured thresholds (e.g. −5 points
          over 2 weeks). Push delivery uses Firebase Cloud Messaging via <code className="text-white/70">POST /api/notifications</code>.
        </div>
      </Card>

      <div className="mt-6">
        <DisclaimerBanner />
      </div>
    </MotionPage>
  );
}
